import Foundation

enum MockMeals {
    static let all: [Meal] = [
        Meal(
            id: "grilled-chicken-bowl",
            name: "Grilled Chicken Bowl",
            imageName: "fork.knife",
            imageAsset: "000",
            cuisine: "American",
            calories: 520,
            protein: 42,
            carbs: 48,
            fat: 18,
            description: "Grilled chicken breast served with brown rice and vegetables.",
            category: "Lunch"
        ),
        Meal(
            id: "oven-baked-salmon-with-lemon",
            name: "Oven Baked Salmon with Lemon",
            imageName: "fork.knife",
            imageAsset: "dinner_000",
            cuisine: "Mediterranean",
            calories: 520,
            protein: 36,
            carbs: 14,
            fat: 32,
            description: "Oven-baked salmon finished with fresh lemon and herbs.",
            category: "Dinner"
        ),
        Meal(
            id: "turkish-style-chicken-saute",
            name: "Turkish Style Chicken Saute",
            imageName: "fork.knife",
            imageAsset: "dinner_001",
            cuisine: "Turkish",
            calories: 480,
            protein: 36,
            carbs: 28,
            fat: 20,
            description: "Chicken sauteed with peppers, tomatoes, and olive oil.",
            category: "Dinner"
        ),
        Meal(
            id: "beef-stew-with-vegetables",
            name: "Beef Stew with Vegetables",
            imageName: "fork.knife",
            imageAsset: "dinner_002",
            cuisine: "International",
            calories: 560,
            protein: 38,
            carbs: 32,
            fat: 26,
            description: "Slow-simmered beef with carrots, potatoes, and herbs.",
            category: "Dinner"
        ),
        Meal(
            id: "baked-eggplant-with-minced-meat",
            name: "Baked Eggplant with Minced Meat",
            imageName: "fork.knife",
            imageAsset: "dinner_003",
            cuisine: "Turkish",
            calories: 540,
            protein: 32,
            carbs: 24,
            fat: 34,
            description: "Roasted eggplant topped with savory minced meat sauce.",
            category: "Dinner"
        ),
        Meal(
            id: "creamy-spinach-chicken",
            name: "Creamy Spinach Chicken",
            imageName: "fork.knife",
            imageAsset: "dinner_004",
            cuisine: "American",
            calories: 510,
            protein: 40,
            carbs: 12,
            fat: 30,
            description: "Chicken in a light cream sauce with wilted spinach.",
            category: "Dinner"
        ),
        Meal(
            id: "oven-roasted-vegetables-with-feta",
            name: "Oven Roasted Vegetables with Feta",
            imageName: "fork.knife",
            imageAsset: "dinner_005",
            cuisine: "Mediterranean",
            calories: 420,
            protein: 16,
            carbs: 38,
            fat: 22,
            description: "Seasonal vegetables roasted with feta and olive oil.",
            category: "Dinner"
        ),
        Meal(
            id: "homemade-chicken-schnitzel",
            name: "Homemade Chicken Schnitzel",
            imageName: "fork.knife",
            imageAsset: "dinner_006",
            cuisine: "German",
            calories: 590,
            protein: 42,
            carbs: 36,
            fat: 28,
            description: "Crispy breaded chicken served with lemon wedges.",
            category: "Dinner"
        ),
        Meal(
            id: "zucchini-boats-with-ground-beef",
            name: "Zucchini Boats with Ground Beef",
            imageName: "fork.knife",
            imageAsset: "dinner_007",
            cuisine: "Mediterranean",
            calories: 470,
            protein: 30,
            carbs: 16,
            fat: 30,
            description: "Baked zucchini filled with seasoned ground beef.",
            category: "Dinner"
        ),
        Meal(
            id: "rice-pilaf-with-chickpeas",
            name: "Rice Pilaf with Chickpeas",
            imageName: "fork.knife",
            imageAsset: "dinner_008",
            cuisine: "Middle Eastern",
            calories: 520,
            protein: 16,
            carbs: 78,
            fat: 14,
            description: "Fluffy rice pilaf with chickpeas and warm spices.",
            category: "Dinner"
        ),
        Meal(
            id: "baked-pasta-with-cheese",
            name: "Baked Pasta with Cheese",
            imageName: "fork.knife",
            imageAsset: "dinner_009",
            cuisine: "Italian",
            calories: 610,
            protein: 22,
            carbs: 78,
            fat: 26,
            description: "Baked pasta with a creamy cheese blend and herbs.",
            category: "Dinner"
        ),
        Meal(
            id: "beef-stir-fry",
            name: "Beef Stir Fry",
            imageName: "fork.knife",
            imageAsset: "001",
            cuisine: "Asian",
            calories: 560,
            protein: 34,
            carbs: 46,
            fat: 22,
            description: "Stir-fried beef with colorful vegetables and a light soy glaze.",
            category: "Lunch"
        ),
        Meal(
            id: "chicken-wrap",
            name: "Chicken Wrap",
            imageName: "fork.knife",
            imageAsset: "002",
            cuisine: "Mediterranean",
            calories: 450,
            protein: 30,
            carbs: 40,
            fat: 16,
            description: "Whole wheat wrap with grilled chicken, yogurt sauce, and greens.",
            category: "Lunch"
        ),
        Meal(
            id: "falafel-plate",
            name: "Falafel Plate",
            imageName: "fork.knife",
            imageAsset: "003",
            cuisine: "Middle Eastern",
            calories: 510,
            protein: 21,
            carbs: 52,
            fat: 24,
            description: "Crispy falafel with hummus, salad, and pita.",
            category: "Lunch"
        ),
        Meal(
            id: "chicken-caesar-salad",
            name: "Chicken Caesar Salad",
            imageName: "fork.knife",
            imageAsset: "004",
            cuisine: "American",
            calories: 420,
            protein: 32,
            carbs: 18,
            fat: 24,
            description: "Crisp romaine, grilled chicken, and parmesan with Caesar dressing.",
            category: "Lunch"
        ),
        Meal(
            id: "tuna-salad-bowl",
            name: "Tuna Salad Bowl",
            imageName: "fork.knife",
            imageAsset: "005",
            cuisine: "Mediterranean",
            calories: 430,
            protein: 32,
            carbs: 22,
            fat: 22,
            description: "Tuna salad with fresh greens, beans, and olive oil.",
            category: "Lunch"
        ),
        Meal(
            id: "falafel-wrap",
            name: "Falafel Wrap",
            imageName: "fork.knife",
            imageAsset: "006",
            cuisine: "Middle Eastern",
            calories: 470,
            protein: 18,
            carbs: 58,
            fat: 18,
            description: "Falafel wrap with tahini sauce and salad.",
            category: "Lunch"
        ),
        Meal(
            id: "salmon-rice-bowl",
            name: "Salmon Rice Bowl",
            imageName: "fork.knife",
            imageAsset: "007",
            cuisine: "Japanese",
            calories: 560,
            protein: 34,
            carbs: 54,
            fat: 20,
            description: "Salmon over rice with cucumber and sesame.",
            category: "Lunch"
        ),
        Meal(
            id: "chicken-burrito-bowl",
            name: "Chicken Burrito Bowl",
            imageName: "fork.knife",
            imageAsset: "008",
            cuisine: "Mexican",
            calories: 610,
            protein: 40,
            carbs: 62,
            fat: 18,
            description: "Chicken, rice, beans, and fresh toppings in a bowl.",
            category: "Lunch"
        ),
        Meal(
            id: "pasta-tomato-sauce",
            name: "Pasta Tomato Sauce",
            imageName: "fork.knife",
            imageAsset: "009",
            cuisine: "Italian",
            calories: 540,
            protein: 16,
            carbs: 78,
            fat: 16,
            description: "Pasta with rich tomato sauce and herbs.",
            category: "Lunch"
        ),
        Meal(
            id: "vegetable-pasta",
            name: "Vegetable Pasta",
            imageName: "fork.knife",
            imageAsset: "010",
            cuisine: "Italian",
            calories: 520,
            protein: 14,
            carbs: 76,
            fat: 14,
            description: "Pasta tossed with seasonal vegetables and olive oil.",
            category: "Lunch"
        ),
        Meal(
            id: "rice-chicken-plate",
            name: "Rice Chicken Plate",
            imageName: "fork.knife",
            imageAsset: "011",
            cuisine: "International",
            calories: 590,
            protein: 38,
            carbs: 64,
            fat: 18,
            description: "Grilled chicken with rice and vegetables.",
            category: "Lunch"
        ),
        Meal(
            id: "mushroom-cheese-toast",
            name: "Mushroom Cheese Toast",
            imageName: "fork.knife",
            imageAsset: "012",
            cuisine: "International",
            calories: 460,
            protein: 18,
            carbs: 46,
            fat: 22,
            description: "Toasted bread with sautéed mushrooms and melted cheese.",
            category: "Lunch"
        ),
        Meal(
            id: "meatball-plate",
            name: "Meatball Plate",
            imageName: "fork.knife",
            imageAsset: "013",
            cuisine: "Italian",
            calories: 620,
            protein: 36,
            carbs: 48,
            fat: 28,
            description: "Baked meatballs with tomato sauce and herbs.",
            category: "Lunch"
        ),
        Meal(
            id: "scrambled-eggs",
            name: "Scrambled Eggs",
            imageName: "fork.knife",
            imageAsset: "bfast_01_scramble",
            cuisine: "American",
            calories: 320,
            protein: 20,
            carbs: 2,
            fat: 24,
            description: "Soft scrambled eggs cooked with olive oil.",
            category: "Breakfast"
        ),
        Meal(
            id: "pancakes",
            name: "Pancakes",
            imageName: "fork.knife",
            imageAsset: "bfast_02_pancakes",
            cuisine: "American",
            calories: 420,
            protein: 10,
            carbs: 68,
            fat: 12,
            description: "Fluffy pancakes served with maple syrup.",
            category: "Breakfast"
        ),
        Meal(
            id: "eggs-and-sausage",
            name: "Eggs & Sausage",
            imageName: "fork.knife",
            imageAsset: "bfast_03_eggs_sausage",
            cuisine: "American",
            calories: 450,
            protein: 22,
            carbs: 6,
            fat: 34,
            description: "Fried eggs served with grilled sausages.",
            category: "Breakfast"
        ),
        Meal(
            id: "banana-toast",
            name: "Banana Toast",
            imageName: "fork.knife",
            imageAsset: "bfast_04_banana_toast",
            cuisine: "American",
            calories: 310,
            protein: 9,
            carbs: 45,
            fat: 10,
            description: "Toasted bread topped with banana slices.",
            category: "Breakfast"
        ),
        Meal(
            id: "avocado-egg-toast",
            name: "Avocado Egg Toast",
            imageName: "fork.knife",
            imageAsset: "bfast_05_avocado_egg",
            cuisine: "American",
            calories: 390,
            protein: 16,
            carbs: 34,
            fat: 20,
            description: "Toasted sourdough topped with avocado and eggs.",
            category: "Breakfast"
        ),
        Meal(
            id: "granola-bowl",
            name: "Granola Bowl",
            imageName: "fork.knife",
            imageAsset: "bfast_06_granola_bowl",
            cuisine: "International",
            calories: 360,
            protein: 14,
            carbs: 52,
            fat: 12,
            description: "Crunchy granola with yogurt and fruits.",
            category: "Breakfast"
        ),
        Meal(
            id: "yogurt-with-nuts",
            name: "Yogurt with Nuts",
            imageName: "fork.knife",
            imageAsset: "bfast_07_yogurt_nuts",
            cuisine: "International",
            calories: 280,
            protein: 15,
            carbs: 20,
            fat: 14,
            description: "Greek yogurt topped with mixed nuts.",
            category: "Breakfast"
        ),
        Meal(
            id: "chia-pudding",
            name: "Chia Pudding",
            imageName: "fork.knife",
            imageAsset: "bfast_08_chia_pudding",
            cuisine: "International",
            calories: 300,
            protein: 9,
            carbs: 32,
            fat: 16,
            description: "Chia seed pudding with fresh fruits.",
            category: "Breakfast"
        ),
        Meal(
            id: "french-toast",
            name: "French Toast",
            imageName: "fork.knife",
            imageAsset: "bfast_10_french_toast",
            cuisine: "American",
            calories: 410,
            protein: 12,
            carbs: 58,
            fat: 14,
            description: "Golden french toast with syrup.",
            category: "Breakfast"
        ),
        Meal(
            id: "shakshuka",
            name: "Shakshuka",
            imageName: "fork.knife",
            imageAsset: "bfast_12_shakshuka",
            cuisine: "Middle Eastern",
            calories: 430,
            protein: 20,
            carbs: 22,
            fat: 28,
            description: "Eggs poached in spicy tomato sauce.",
            category: "Breakfast"
        ),
        Meal(
            id: "avocado-toast",
            name: "Avocado Toast",
            imageName: "fork.knife",
            imageAsset: "bfast_13_avocado_toast",
            cuisine: "American",
            calories: 350,
            protein: 10,
            carbs: 36,
            fat: 18,
            description: "Toasted bread topped with smashed avocado.",
            category: "Breakfast"
        ),
        Meal(
            id: "fruit-yogurt-cup",
            name: "Fruit Yogurt Cup",
            imageName: "cup.and.saucer",
            imageAsset: nil,
            cuisine: "International",
            calories: 260,
            protein: 17,
            carbs: 28,
            fat: 8,
            description: "Creamy yogurt with fresh fruit and a touch of honey—light and refreshing.",
            category: "Snack"
        ),
        Meal(
            id: "dark-chocolate-mousse",
            name: "Dark Chocolate Mousse",
            imageName: "birthday.cake",
            imageAsset: nil,
            cuisine: "French",
            calories: 410,
            protein: 7,
            carbs: 36,
            fat: 26,
            description: "Rich, airy chocolate mousse finished with cocoa dusting.",
            category: "Dessert"
        )
    ]
}

