import Foundation

enum MockMeals {
    static let all: [Meal] = [
        Meal(
            id: "grilled-chicken-bowl",
            name: "Grilled Chicken Bowl",
            imageName: "fork.knife.circle.fill",
            imageAsset: nil,
            cuisine: "American",
            calories: 520,
            protein: 42,
            carbs: 48,
            fat: 18,
            description: "Grilled chicken breast served with brown rice, avocado, and seasonal vegetables. High-protein and balanced.",
            category: "Lunch"
        ),
        Meal(
            id: "creamy-mushroom-pasta",
            name: "Creamy Mushroom Pasta",
            imageName: "fork.knife",
            imageAsset: nil,
            cuisine: "Italian",
            calories: 610,
            protein: 18,
            carbs: 72,
            fat: 24,
            description: "Pasta with creamy mushroom sauce, garlic, and parmesan cheese. Comfort food with rich flavor.",
            category: "Dinner"
        ),
        Meal(
            id: "baked-salmon-veggies",
            name: "Baked Salmon & Veggies",
            imageName: "fish",
            imageAsset: nil,
            cuisine: "Mediterranean",
            calories: 480,
            protein: 38,
            carbs: 32,
            fat: 22,
            description: "Oven-baked salmon with olive oil roasted vegetables. Rich in omega-3.",
            category: "Dinner"
        ),
        Meal(
            id: "chicken-wrap",
            name: "Chicken Wrap",
            imageName: "fork.knife.circle",
            imageAsset: nil,
            cuisine: "Mediterranean",
            calories: 450,
            protein: 30,
            carbs: 40,
            fat: 16,
            description: "Whole wheat wrap with grilled chicken, yogurt sauce, and fresh greens.",
            category: "Lunch"
        ),
        Meal(
            id: "lentil-curry",
            name: "Lentil Curry",
            imageName: "leaf",
            imageAsset: nil,
            cuisine: "Indian",
            calories: 430,
            protein: 22,
            carbs: 58,
            fat: 12,
            description: "Spiced red lentil curry cooked with coconut milk and herbs.",
            category: "Dinner"
        ),
        Meal(
            id: "homemade-beef-burger",
            name: "Homemade Beef Burger",
            imageName: "takeoutbag.and.cup.and.straw",
            imageAsset: nil,
            cuisine: "American",
            calories: 680,
            protein: 36,
            carbs: 45,
            fat: 38,
            description: "Juicy beef patty with cheddar cheese and homemade sauce.",
            category: "Dinner"
        ),
        Meal(
            id: "falafel-plate",
            name: "Falafel Plate",
            imageName: "leaf.circle",
            imageAsset: nil,
            cuisine: "Middle Eastern",
            calories: 510,
            protein: 21,
            carbs: 52,
            fat: 24,
            description: "Crispy falafel with hummus, salad, and pita bread.",
            category: "Lunch"
        ),
        Meal(
            id: "teriyaki-chicken-rice",
            name: "Teriyaki Chicken Rice",
            imageName: "takeoutbag.and.cup.and.straw.fill",
            imageAsset: nil,
            cuisine: "Japanese",
            calories: 560,
            protein: 34,
            carbs: 62,
            fat: 16,
            description: "Sweet and savory teriyaki chicken served over steamed rice.",
            category: "Dinner"
        ),
        Meal(
            id: "scrambled-eggs",
            name: "Scrambled Eggs",
            imageName: "fork.knife",
            imageAsset: "bfast_01_scramble",
            cuisine: "American",
            calories: 320,
            protein: 20,
            carbs: 2,
            fat: 24,
            description: "Soft scrambled eggs cooked with olive oil.",
            category: "Breakfast"
        ),
        Meal(
            id: "pancakes",
            name: "Pancakes",
            imageName: "fork.knife",
            imageAsset: "bfast_02_pancakes",
            cuisine: "American",
            calories: 420,
            protein: 10,
            carbs: 68,
            fat: 12,
            description: "Fluffy pancakes served with maple syrup.",
            category: "Breakfast"
        ),
        Meal(
            id: "eggs-and-sausage",
            name: "Eggs & Sausage",
            imageName: "fork.knife",
            imageAsset: "bfast_03_eggs_sausage",
            cuisine: "American",
            calories: 450,
            protein: 22,
            carbs: 6,
            fat: 34,
            description: "Fried eggs served with grilled sausages.",
            category: "Breakfast"
        ),
        Meal(
            id: "banana-toast",
            name: "Banana Toast",
            imageName: "fork.knife",
            imageAsset: "bfast_04_banana_toast",
            cuisine: "American",
            calories: 310,
            protein: 9,
            carbs: 45,
            fat: 10,
            description: "Toasted bread topped with banana slices.",
            category: "Breakfast"
        ),
        Meal(
            id: "avocado-egg-toast",
            name: "Avocado Egg Toast",
            imageName: "fork.knife",
            imageAsset: "bfast_05_avocado_egg",
            cuisine: "American",
            calories: 390,
            protein: 16,
            carbs: 34,
            fat: 20,
            description: "Toasted sourdough topped with avocado and eggs.",
            category: "Breakfast"
        ),
        Meal(
            id: "granola-bowl",
            name: "Granola Bowl",
            imageName: "fork.knife",
            imageAsset: "bfast_06_granola_bowl",
            cuisine: "International",
            calories: 360,
            protein: 14,
            carbs: 52,
            fat: 12,
            description: "Crunchy granola with yogurt and fruits.",
            category: "Breakfast"
        ),
        Meal(
            id: "yogurt-with-nuts",
            name: "Yogurt with Nuts",
            imageName: "fork.knife",
            imageAsset: "bfast_07_yogurt_nuts",
            cuisine: "International",
            calories: 280,
            protein: 15,
            carbs: 20,
            fat: 14,
            description: "Greek yogurt topped with mixed nuts.",
            category: "Breakfast"
        ),
        Meal(
            id: "chia-pudding",
            name: "Chia Pudding",
            imageName: "fork.knife",
            imageAsset: "bfast_08_chia_pudding",
            cuisine: "International",
            calories: 300,
            protein: 9,
            carbs: 32,
            fat: 16,
            description: "Chia seed pudding with fresh fruits.",
            category: "Breakfast"
        ),
        Meal(
            id: "french-toast",
            name: "French Toast",
            imageName: "fork.knife",
            imageAsset: "bfast_10_french_toast",
            cuisine: "American",
            calories: 410,
            protein: 12,
            carbs: 58,
            fat: 14,
            description: "Golden french toast with syrup.",
            category: "Breakfast"
        ),
        Meal(
            id: "shakshuka",
            name: "Shakshuka",
            imageName: "fork.knife",
            imageAsset: "bfast_12_shakshuka",
            cuisine: "Middle Eastern",
            calories: 430,
            protein: 20,
            carbs: 22,
            fat: 28,
            description: "Eggs poached in spicy tomato sauce.",
            category: "Breakfast"
        ),
        Meal(
            id: "avocado-toast",
            name: "Avocado Toast",
            imageName: "fork.knife",
            imageAsset: "bfast_13_avocado_toast",
            cuisine: "American",
            calories: 350,
            protein: 10,
            carbs: 36,
            fat: 18,
            description: "Toasted bread topped with smashed avocado.",
            category: "Breakfast"
        ),
        Meal(
            id: "fruit-yogurt-cup",
            name: "Fruit Yogurt Cup",
            imageName: "cup.and.saucer",
            imageAsset: nil,
            cuisine: "International",
            calories: 260,
            protein: 17,
            carbs: 28,
            fat: 8,
            description: "Creamy yogurt with fresh fruit and a touch of honey—light and refreshing.",
            category: "Snack"
        ),
        Meal(
            id: "dark-chocolate-mousse",
            name: "Dark Chocolate Mousse",
            imageName: "birthday.cake",
            imageAsset: nil,
            cuisine: "French",
            calories: 410,
            protein: 7,
            carbs: 36,
            fat: 26,
            description: "Rich, airy chocolate mousse finished with cocoa dusting.",
            category: "Dessert"
        )
    ]
}

